name: Run Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run unit tests
      run: |
        echo "{}" > './test-local.settings.json'
        python3 -m unittest discover -s tests -p 'test_*.py'
